version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
      args:
        DATABASE_URL: jdbc:postgresql://db:5432/arc
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
        DATABASE_RESTRICTED_USER: arc_restricted
        APPLICATION_DIRECTORY: ./
        DISABLE_DEBUG_GUI : y
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: arc
    ports:
      - 5432:5432

