apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcWeb.fullname" . }}
  labels:
    {{- include "arcWeb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.imageWeb.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "arcWeb.fullname" . }}
