apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcWs.fullname" . }}
  labels:
    {{- include "arcWs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.imageWs.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "arcWs.fullname" . }}