name: ARC CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  check:
     runs-on: ubuntu-latest
     steps:
       - run: echo $GITHUB_EVENT_NAME $GITHUB_REF $GITHUB_EVENT_RELEASE_TAG_NAME
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify with Maven
      run: mvn verify
  push_to_registry:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'release'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Push arc-web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./app.Dockerfile
          tags: |
            ${{ github.event_name == 'release' && "lecorrepierre/arc:$GITHUB_EVENT_RELEASE_TAG_NAME" || '' }}
            ${{ github.ref == 'refs/heads/master' && 'lecorrepierre/arc:latest' || '' }}
      - name: Push arc-ws to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./app-ws.Dockerfile
          tags: |
            ${{ github.event_name == 'release' && "lecorrepierre/arc:$GITHUB_EVENT_RELEASE_TAG_NAME" || '' }}
            ${{ github.ref == 'refs/heads/master' && 'lecorrepierre/arc-ws:latest' || '' }}
